name: messenger
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  states_rebuilder: ^6.4.0
  forui: ^0.16.0
  flutter:
    sdk: flutter
  hive_flutter: ^1.1.0
  uuid: ^4.4.0
  package_info_plus: ^9.0.0
  path_provider: ^2.1.3
  flutter_native_splash: ^2.4.1
  shared_preferences: ^2.5.3
  spark:
    path: C://Users//Adn//CascadeProjects//spark
  manager_client:
    path: D://03 Projects//applications//manager//manager_client

flutter:
  uses-material-design: true
  # assets:fl
  # - assets/images/