// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'chats/chat.dart';
import 'messages/messages_repository.dart';
import 'users/users_repository.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 4040832263671785829),
      name: 'Message',
      lastPropertyId: const obx_int.IdUid(7, 1553826477650427963),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 963738851617642567),
            name: 'id',
            type: 6,
            flags: 129),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 475702768723334191),
            name: 'content',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 88923895736322368),
            name: 'timestamp',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 3863581725200929896),
            name: 'senderId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(1, 8772555349135881714),
            relationTarget: 'User'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 4685526580438024635),
            name: 'chatId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(3, 8787987809022275585),
            relationTarget: 'Chat'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 1553826477650427963),
            name: 'receiverId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(6, 1974759787810757098),
            relationTarget: 'User')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 5956886671080797657),
      name: 'User',
      lastPropertyId: const obx_int.IdUid(4, 986124181742385804),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5579859904909509527),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6884138452139547495),
            name: 'email',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2983940671108647891),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 986124181742385804),
            name: 'password',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'chats', srcEntity: 'Chat', srcField: 'user')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 4063800593209743367),
      name: 'Chat',
      lastPropertyId: const obx_int.IdUid(5, 8858720632141977890),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6133130133360783571),
            name: 'id',
            type: 6,
            flags: 129),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7013710659436716055),
            name: 'senderId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(4, 8473186670691030539),
            relationTarget: 'User'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8858720632141977890),
            name: 'userId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(7, 5522855384153370733),
            relationTarget: 'User')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'messages', srcEntity: 'Message', srcField: 'chat')
      ])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(3, 4063800593209743367),
      lastIndexId: const obx_int.IdUid(7, 5522855384153370733),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [739958185133536252, 8530641776271443159],
      retiredPropertyUids: const [
        3522929536028055756,
        9070032870101372707,
        3608530342429008363
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Message: obx_int.EntityDefinition<Message>(
        model: _entities[0],
        toOneRelations: (Message object) =>
            [object.sender, object.chat, object.receiver],
        toManyRelations: (Message object) => {},
        getId: (Message object) => object.id,
        setId: (Message object, int id) {
          object.id = id;
        },
        objectToFB: (Message object, fb.Builder fbb) {
          final contentOffset = fbb.writeString(object.content);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, contentOffset);
          fbb.addInt64(2, object.timestamp.millisecondsSinceEpoch);
          fbb.addInt64(3, object.sender.targetId);
          fbb.addInt64(5, object.chat.targetId);
          fbb.addInt64(6, object.receiver.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Message()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..content = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..timestamp = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0));
          object.sender.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          object.sender.attach(store);
          object.chat.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          object.chat.attach(store);
          object.receiver.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          object.receiver.attach(store);
          return object;
        }),
    User: obx_int.EntityDefinition<User>(
        model: _entities[1],
        toOneRelations: (User object) => [],
        toManyRelations: (User object) => {
              obx_int.RelInfo<Chat>.toOneBacklink(
                      5, object.id, (Chat srcObject) => srcObject.user):
                  object.chats
            },
        getId: (User object) => object.id,
        setId: (User object, int id) {
          object.id = id;
        },
        objectToFB: (User object, fb.Builder fbb) {
          final emailOffset = fbb.writeString(object.email);
          final nameOffset = fbb.writeString(object.name);
          final passwordOffset = fbb.writeString(object.password);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, emailOffset);
          fbb.addOffset(2, nameOffset);
          fbb.addOffset(3, passwordOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = User()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..email = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..name = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..password = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 10, '');
          obx_int.InternalToManyAccess.setRelInfo<User>(
              object.chats,
              store,
              obx_int.RelInfo<Chat>.toOneBacklink(
                  5, object.id, (Chat srcObject) => srcObject.user));
          return object;
        }),
    Chat: obx_int.EntityDefinition<Chat>(
        model: _entities[2],
        toOneRelations: (Chat object) => [object.sender, object.user],
        toManyRelations: (Chat object) => {
              obx_int.RelInfo<Message>.toOneBacklink(
                      6, object.id, (Message srcObject) => srcObject.chat):
                  object.messages
            },
        getId: (Chat object) => object.id,
        setId: (Chat object, int id) {
          object.id = id;
        },
        objectToFB: (Chat object, fb.Builder fbb) {
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.sender.targetId);
          fbb.addInt64(4, object.user.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Chat()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          object.sender.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          object.sender.attach(store);
          object.user.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          object.user.attach(store);
          obx_int.InternalToManyAccess.setRelInfo<Chat>(
              object.messages,
              store,
              obx_int.RelInfo<Message>.toOneBacklink(
                  6, object.id, (Message srcObject) => srcObject.chat));
          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Message] entity fields to define ObjectBox queries.
class Message_ {
  /// See [Message.id].
  static final id =
      obx.QueryIntegerProperty<Message>(_entities[0].properties[0]);

  /// See [Message.content].
  static final content =
      obx.QueryStringProperty<Message>(_entities[0].properties[1]);

  /// See [Message.timestamp].
  static final timestamp =
      obx.QueryDateProperty<Message>(_entities[0].properties[2]);

  /// See [Message.sender].
  static final sender =
      obx.QueryRelationToOne<Message, User>(_entities[0].properties[3]);

  /// See [Message.chat].
  static final chat =
      obx.QueryRelationToOne<Message, Chat>(_entities[0].properties[4]);

  /// See [Message.receiver].
  static final receiver =
      obx.QueryRelationToOne<Message, User>(_entities[0].properties[5]);
}

/// [User] entity fields to define ObjectBox queries.
class User_ {
  /// See [User.id].
  static final id = obx.QueryIntegerProperty<User>(_entities[1].properties[0]);

  /// See [User.email].
  static final email =
      obx.QueryStringProperty<User>(_entities[1].properties[1]);

  /// See [User.name].
  static final name = obx.QueryStringProperty<User>(_entities[1].properties[2]);

  /// See [User.password].
  static final password =
      obx.QueryStringProperty<User>(_entities[1].properties[3]);

  /// see [User.chats]
  static final chats = obx.QueryBacklinkToMany<Chat, User>(Chat_.user);
}

/// [Chat] entity fields to define ObjectBox queries.
class Chat_ {
  /// See [Chat.id].
  static final id = obx.QueryIntegerProperty<Chat>(_entities[2].properties[0]);

  /// See [Chat.sender].
  static final sender =
      obx.QueryRelationToOne<Chat, User>(_entities[2].properties[1]);

  /// See [Chat.user].
  static final user =
      obx.QueryRelationToOne<Chat, User>(_entities[2].properties[2]);

  /// see [Chat.messages]
  static final messages = obx.QueryBacklinkToMany<Message, Chat>(Message_.chat);
}
